services:

  app:
    container_name: ${STACK_NAME}_app
    image: nextcloud:fpm-alpine
    restart: unless-stopped
    networks:
      - default
    volumes:
      - app-data:/var/www/html:z
    environment:
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_HOST=mariadb
    depends_on:
      - mariadb
      - redis

  mariadb:
    container_name: ${STACK_NAME}_db
    image: mariadb:10.6
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - mariadb-data:/var/lib/mysql:Z
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}

  nginx:
    container_name: ${STACK_NAME}_nginx
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - app-data:/var/www/html:z,ro
      - nginx-config:/etc/nginx
    links:
      - app
    networks:
      - default
      - web

  cron:
    container_name: ${STACK_NAME}_cron
    image: nextcloud:fpm-alpine
    restart: unless-stopped
    volumes:
      - app-data:/var/www/html:z
    user: root
    entrypoint: /cron.sh
    depends_on:
      - mariadb

  redis:
    container_name: ${STACK_NAME}_redis
    image: redis:alpine
    restart: unless-stopped

volumes:
  app-data:
  mariadb-data:
  nginx-config:

networks:
  web:
    external: true