services:

  app:
    container_name: radarr_app
    image: ghcr.io/linuxserver/radarr:latest
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    networks:
      - web
    volumes:
      - app-data:/config:rw
      - /var/lib/docker/volumes/shared_media/_data/movies:/movies:rw
      - /var/lib/docker/volumes/shared_media/_data/downloads:/downloads:rw
    # ports:
      # - 7878:7878

volumes:
  app-data:

networks:
  web:
    external: true