services:

  app:
    container_name: homarr_app
    image: ghcr.io/homarr-labs/homarr:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - app-data:/appdata
    environment:
      - SECRET_ENCRYPTION_KEY=${SECRET_ENCRYPTION_KEY}
    #ports:
    #  - 7575:7575
    networks:
      - web

volumes:
  app-data:

networks:
  web:
    external: true