services:

  app:
    container_name: cup_app
    image: ghcr.io/sergi0g/cup:latest
    restart: unless-stopped
    command: serve
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    # ports:
    #   - 8000:8000
    networks:
      - web

networks:
  web:
    external: true