
services:
  homepage:
    container_name: homepage
    image: ghcr.io/gethomepage/homepage:latest
    restart: unless-stopped
    volumes:
      - ./config:/config
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - web
    environment:
      - TZ=Europe/Paris

networks:
  web:
    external: true