services:

  app:
    image: fnsys/dockhand:latest
    restart: unless-stopped
    networks:
      - web
    ports:
      - 3000:3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/homelab:/opt/homelab
      - app_data:/app/data

volumes:
  app_data:

networks:
  web:
    external: true