services:

  app:
    image: vaultwarden/server:latest
    restart: unless-stopped
    volumes:
      - app-data:/data:rw
    networks:
      - web
    # ports:
    #   - 80:80
    environment:
      - SIGNUPS_ALLOWED=${SIGNUPS_ALLOWED}

volumes:
  app-data:

networks:
  web:
    external: true