services:

  app:
    image: vaultwarden/server:latest
    container_name: ${STACK_NAME}_app
    restart: unless-stopped
    volumes:
      - app-data:/data:rw
    networks:
      - web
    environment:
      - SIGNUPS_ALLOWED=false

volumes:
  app-data:

networks:
  web:
    external: true