services:

  app:
    container_name: open-webui_app
    image: ghcr.io/open-webui/open-webui:latest
    restart: unless-stopped
    volumes:
      - app-data:/app/backend/data
    networks:
      - web

volumes:
  app-data:

networks:
  web:
    external: true