services:

  app:
    container_name: open-webui_app
    image: ghcr.io/open-webui/open-webui:main
    restart: unless-stopped
    volumes:
      - app-data:/app/backend/data
    networks:
      - default
      - web
    # ports:
    #   - 8000:8000
    environment:
      - WEBUI_SECRET_KEY=${WEBUI_SECRET_KEY:-}
      - OLLAMA_BASE_URL=http://ollama:11434
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  ollama:
    container_name: open-webui_ollama
    image: ollama/ollama:latest
    restart: unless-stopped
    volumes:
      - ollama-data:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  open-terminal:
    container_name: open-webui_open-terminal
    image: ghcr.io/open-webui/open-terminal:latest
    restart: unless-stopped
    environment:
      - OPEN_TERMINAL_API_KEY=${OPEN_TERMINAL_API_KEY:-}
      - OPEN_TERMINAL_PACKAGES=${OPEN_TERMINAL_PACKAGES:-}
      - OPEN_TERMINAL_PIP_PACKAGES=${OPEN_TERMINAL_PIP_PACKAGES:-}
      - OPEN_TERMINAL_NPM_PACKAGES=${OPEN_TERMINAL_NPM_PACKAGES:-}
    ports:
      - 8000:8000
    volumes:
      - open-terminal-data:/home/user


volumes:
  app-data:
  ollama-data:
  open-terminal-data:

networks:
  web:
    external: true