services:

  app:
    container_name: open-webui_app
    image: ghcr.io/open-webui/open-webui:latest
    restart: unless-stopped
    volumes:
      - open-webui-data:/app/backend/data
    networks:
      - default
      - web
    extra_hosts:
      - host.docker.internal:host-gateway

volumes:
  open-webui-data:

networks:
  web:
    external: true