services:

  app:
    container_name: wallos_app
    image: bellamy/wallos:latest
    restart: unless-stopped
    environment:
      - TZ=${TZ}
    volumes:
      - app-db:/var/www/html/db:rw
      - app-logos:/var/www/html/images/uploads/logos:rw
    networks:
      - web
    # ports:
    #   - 80:80

volumes:
  app-db:
  app-logos:

networks:
  web:
    external: true