
services:
  app:
    image: ghcr.io/gethomepage/homepage:latest
    restart: unless-stopped
    volumes:
      - ./config:/config
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=${TZ}
      - HOMEPAGE_ALLOWED_HOSTS=${HOMEPAGE_ALLOWED_HOSTS}
      - HOMEPAGE_VAR_DOMAIN=${HOMEPAGE_VAR_DOMAIN}
      - HOMEPAGE_VAR_GITEA_API_KEY=${HOMEPAGE_VAR_GITEA_API_KEY}
      - HOMEPAGE_VAR_NEXTCLOUD_APP_PASSWORD=${HOMEPAGE_VAR_NEXTCLOUD_APP_PASSWORD}
      - HOMEPAGE_VAR_PAPERLESS_NGX_APP_PASSWORD=${HOMEPAGE_VAR_PAPERLESS_NGX_APP_PASSWORD}
      - HOMEPAGE_VAR_IMMICH_APP_PASSWORD=${HOMEPAGE_VAR_IMMICH_APP_PASSWORD}
      - HOMEPAGE_VAR_ADGUARD_HOME_USERNAME=${HOMEPAGE_VAR_ADGUARD_HOME_USERNAME}
      - HOMEPAGE_VAR_ADGUARD_HOME_PASSWORD=${HOMEPAGE_VAR_ADGUARD_HOME_PASSWORD}
      - HOMEPAGE_VAR_WIREGUARD_EASY_APP_PASSWORD=${HOMEPAGE_VAR_WIREGUARD_EASY_APP_PASSWORD}
      - HOMEPAGE_VAR_MEALIE_APP_PASSWORD=${HOMEPAGE_VAR_MEALIE_APP_PASSWORD}
      - HOMEPAGE_VAR_JELLYFIN_APP_PASSWORD=${HOMEPAGE_VAR_JELLYFIN_APP_PASSWORD}
      - HOMEPAGE_VAR_JELLYSEERR_APP_PASSWORD=${HOMEPAGE_VAR_JELLYSEERR_APP_PASSWORD}
      - HOMEPAGE_VAR_LIDARR_APP_PASSWORD=${HOMEPAGE_VAR_LIDARR_APP_PASSWORD}
      - HOMEPAGE_VAR_RADARR_APP_PASSWORD=${HOMEPAGE_VAR_RADARR_APP_PASSWORD}
      - HOMEPAGE_VAR_SONARR_APP_PASSWORD=${HOMEPAGE_VAR_SONARR_APP_PASSWORD}
      - HOMEPAGE_VAR_PROWLARR_APP_PASSWORD=${HOMEPAGE_VAR_PROWLARR_APP_PASSWORD}
      - HOMEPAGE_VAR_QBITTORRENT_APP_USERNAME=${HOMEPAGE_VAR_QBITTORRENT_APP_USERNAME}
      - HOMEPAGE_VAR_QBITTORRENT_APP_PASSWORD=${HOMEPAGE_VAR_QBITTORRENT_APP_PASSWORD}
      - HOMEPAGE_VAR_PROXMOX_API_KEY=${HOMEPAGE_VAR_PROXMOX_API_KEY}
      - HOMEPAGE_VAR_PROXMOX_API_TOKEN=${HOMEPAGE_VAR_PROXMOX_API_TOKEN}
      - HOMEPAGE_VAR_PROXMOX_URL=${HOMEPAGE_VAR_PROXMOX_URL}
      - HOMEPAGE_VAR_CADDY_APP_HOST=${HOMEPAGE_VAR_CADDY_APP_HOST}
      - HOMEPAGE_VAR_WG_EASY_USERNAME=${HOMEPAGE_VAR_WG_EASY_USERNAME}
      - HOMEPAGE_VAR_WG_EASY_PASSWORD=${HOMEPAGE_VAR_WG_EASY_PASSWORD}
    # ports:
    #   - 3000:3000
    networks:
      - web

networks:
  web:
    external: true