
services:
  app:
    container_name: homepage_app
    image: ghcr.io/gethomepage/homepage:latest
    restart: unless-stopped
    volumes:
      - app-config:/config
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=${TZ}
      - HOMEPAGE_ALLOWED_HOSTS=${HOMEPAGE_ALLOWED_HOSTS}
    # ports:
    #   - 3000:3000
    networks:
      - web

volumes:
  app-config:

networks:
  web:
    external: true