services:
  postgres:
    image: docker.io/library/postgres:14
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data:rw

  app:
    image: codeberg.org/forgejo/forgejo:15
    restart: unless-stopped
    volumes:
      - app-data:/data:rw
      - /etc/localtime:/etc/localtime:ro
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - FORGEJO__database__DB_TYPE=postgres
      - FORGEJO__database__DB_HOST=postgres:5432
      - FORGEJO__database__DB_NAME=${DB_NAME}
      - FORGEJO__database__DB_USER=${DB_USER}
      - FORGEJO__database__DB_PASSWD=${DB_PASSWORD}
    depends_on:
      - postgres
    ports:
      - 222:222
      - 3000:3000

  runner:
    image: code.forgejo.org/forgejo/runner:6
    restart: unless-stopped
    depends_on:
      - app
    volumes:
      - runner-data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - FORGEJO_INSTANCE_URL=http://app:3000
      - FORGEJO_RUNNER_UUID=${FORGEJO_RUNNER_UUID}
      - FORGEJO_RUNNER_SECRET=${FORGEJO_RUNNER_SECRET}
      - FORGEJO_RUNNER_NAME=main

volumes:
  app-data:
  postgres-data:
