services:

  app:
    container_name: qbittorrent_app
    image: ghcr.io/linuxserver/qbittorrent:latest
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - app-config:/config:rw
      - /var/lib/docker/volumes/shared_media/_data/downloads:/downloads:rw
    # ports:
      # - 8080:8080 # web UI port
      # - 6881:6881/udp # torrenting port
    network_mode: service:gluetun
    depends_on:
      gluetun:
        condition: service_healthy
        restart: true

  gluetun:
    container_name: qbittorrent_gluetun
    image: qmcgaw/gluetun:latest
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER}
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESSES}
    healthcheck:
      test: ping -c 1 www.google.com || exit 1
      interval: 20s
      timeout: 10s
      retries: 5
    networks:
      - web

volumes:
  app-config:

networks:
  web:
    external: true