services:

  app:
    container_name: crafty_app
    image: registry.gitlab.com/crafty-controller/crafty-4:latest
    restart: unless-stopped
    environment:
        - TZ=${TZ}
    networks:
      - web
    ports:
        - 25565:25565
        - 25566:25566
    volumes:
        - app_backups:/crafty/backups
        - app_logs:/crafty/logs
        - app_servers:/crafty/servers
        - app_config:/crafty/app/config
        - app_import:/crafty/import

volumes:
  app_backups:
  app_logs:
  app_servers:
  app_config:
  app_import:

networks:
  web:
    external: true