services:

  app:
    image: caddy:latest
    restart: unless-stopped
    networks:
      - web
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    volumes:
      - ./conf:/etc/caddy
      - /opt/homelab/stacks:/config/stacks:ro
      - app-data:/data
      - app-config:/config
    environment:
      - TZ=${TZ}
      - DOMAIN=${DOMAIN}
      - ACME_EMAIL=${ACME_EMAIL}

volumes:
  app-data:
  app-config:

networks:
  web:
    external: true