services:

  app:
    image: cloubit/caddy-infomaniak:latest
    restart: unless-stopped
    networks:
      - web
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    volumes:
      - ./conf:/etc/caddy
      - /opt/homelab/stacks:/config/stacks:ro
      - app-data:/data
      - app-config:/config
    environment:
      - TZ=${TZ}
      - DOMAIN=${DOMAIN}
      - INFOMANIAK_API_TOKEN=${INFOMANIAK_API_TOKEN}
      - ACME_EMAIL=${ACME_EMAIL}
      - ALLOWED_IPS=${ALLOWED_IPS}
      - APPS01_HOST=${APPS01_HOST}

volumes:
  app-data:
  app-config:

networks:
  web:
    external: true