services:

  jellyfin:
    image: jellyfin/jellyfin:latest
    restart: unless-stopped
    runtime: nvidia
    volumes:
      - jellyfin-config:/config:rw
      - jellyfin-cache:/cache:rw
      - shared_media:/media:rw
    environment:
      - JELLYFIN_PublishedServerUrl=${JELLYFIN_PublishedServerUrl}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    networks:
      - default
      - web
    ports:
      - 61290:8096
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]


  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - GUID=${PGID}
      - TZ=${TZ}
    volumes:
      - jellyseerr-config:/app/config:rw
    networks:
      - default
      - web
    ports:
     - 52998:5055 # Jellyseerr web interface

  prowlarr:
    image: ghcr.io/linuxserver/prowlarr:latest
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - prowlarr-config:/config:rw
    networks:
      - default
      - web
    ports:
      - 52613:9696 # Prowlarr web interface

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    restart: unless-stopped
    environment:
      - TZ=${TZ}
    networks:
      - default
      - web
    ports:
      - 62758:8191

  radarr:
    image: ghcr.io/linuxserver/radarr:latest
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - radarr-data:/config:rw
      - /var/lib/docker/volumes/shared_media/_data/movies:/movies:rw
      - /var/lib/docker/volumes/shared_media/_data/downloads:/downloads:rw
    networks:
      - default
      - web
    ports:
      - 51437:7878 # Radarr web interface

  sonarr:
    image: ghcr.io/linuxserver/sonarr:latest
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - sonarr-data:/config:rw
      - /var/lib/docker/volumes/shared_media/_data/shows:/shows:rw
      - /var/lib/docker/volumes/shared_media/_data/downloads:/downloads:rw
    networks:
      - default
      - web
    ports:
      - 52560:8989 # Sonarr web interface

  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - GUID=${PGID}
      - TZ=${TZ}
    volumes:
      - lidarr-config:/config:rw
      - /var/lib/docker/volumes/shared_media/_data/music:/music:rw
      - /var/lib/docker/volumes/shared_media/_data/downloads:/downloads:rw
    ports:
      - 61490:8686
    networks:
      - default
      - web

  # dispatcharr:
  #   image: ghcr.io/dispatcharr/dispatcharr:latest
  #   restart: unless-stopped
  #   network_mode: host
  #   volumes:
  #     - dispatcharr-data:/data
  #   environment:
  #     - DISPATCHARR_ENV=aio
  #     - REDIS_HOST=localhost
  #     - CELERY_BROKER_URL=redis://localhost:6379/0
  #     - DISPATCHARR_LOG_LEVEL=info
  #   extra_hosts:
  #     - "mafreebox.freebox.fr:192.168.1.254"
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             count: all
  #             capabilities: [gpu]

  tor:
    image: dockurr/tor:latest
    restart: unless-stopped
    networks:
      - default
      - web
    # ports:
    #   - 9050:9050
    #   - 9051:9051
    volumes:
      - tor-config:/etc/tor:rw
      - tor-data:/var/lib/tor:rw

  gluetun:
    image: qmcgaw/gluetun:latest
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER}
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESSES}
      - HTTP_CONTROL_SERVER_AUTH_DEFAULT_ROLE='{"auth":"apikey","apikey":"${GLUETUN_APIKEY}"}'
    healthcheck:
      test: ping -c 1 www.google.com || exit 1
      interval: 20s
      timeout: 10s
      retries: 5
    networks:
      - default
      - web
    ports:
      - 64935:8080 # Qbittorrent web UI

  qbittorrent:
    image: ghcr.io/linuxserver/qbittorrent:latest
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - qbittorrent-config:/config:rw
      - /var/lib/docker/volumes/shared_media/_data/downloads:/downloads:rw
    network_mode: service:gluetun
    depends_on:
      gluetun:
        condition: service_healthy
        restart: true

  tdarr:
    image: ghcr.io/haveagitgat/tdarr:latest
    restart: unless-stopped
    runtime: nvidia
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - serverIP=0.0.0.0
      - serverPort=8266
      - webUIPort=8265
      - internalNode=true
      - nodeName=MainNode
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - tdarr-config:/app/configs:rw
      - tdarr-server:/app/server:rw
      - tdarr-logs:/app/logs:rw
      - /var/lib/docker/volumes/shared_media/_data/movies:/media/movies:rw
      - /var/lib/docker/volumes/shared_media/_data/shows:/media/shows:rw
      - tdarr-transcode:/temp:rw
    networks:
      - default
      - web
    ports:
      - 62902:8265  # Web UI
    #   - 8266:8266  # Server port
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, video, compute, utility]

volumes:
  jellyfin-config:
  jellyfin-cache:
  jellyseerr-config:
  prowlarr-config:
  radarr-data:
  sonarr-data:
  lidarr-config:
  # dispatcharr-data:
  tor-config:
  tor-data:
  qbittorrent-config:
  tdarr-config:
  tdarr-server:
  tdarr-logs:
  tdarr-transcode:
  shared_media:
    external: true
    name: shared_media

networks:
  web:
    external: true
