services:

  app:
    container_name: bazarr_app
    image: ghcr.io/linuxserver/bazarr:latest
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - app-config:/config:rw
      - /var/lib/docker/volumes/shared_media/_data/movies:/movies:rw
      - /var/lib/docker/volumes/shared_media/_data/shows:/tv:rw
    # ports:
    #   - 6767:6767
    networks:
      - web

volumes:
  app-config:

networks:
  web:
    external: true